main:
  - name: About
    url: '#about'
    weight: 1
  - name: Posts
    url: /posts/
    weight: 2
  - name: Music
    url: /music/#about
    weight: 2
#  - name: Docs
#    url: /docs/
#    weight: 3